### PR TITLE
Invite bors to the party

### PR DESCRIPTION
**Pull request by justanotherdot**
:tada: @jystic

### CODE REVIEW

**Comment by jacobstanley** [comment]
💯

**Comment by notriddle** [comment]
"continuous-integration/appveyor/branch"

You probably want to remove that line, since you're not using appveyor.

**Comment by justanotherdot** [comment]
> You probably want to remove that line, since you're not using appveyor.

ahhh, thanks!

**Comment by justanotherdot** [comment]
Thanks @notriddle!

**Pull request merged**
